### ISSUE TITLE
Crash on osu!laser 2020.717.0

### ISSUE THREAD

**Issue by TechAdvancedCyborg** [swoolcock/rush#40]
Error:
```
[runtime] 2020-07-20 06:39:04 [debug]: Pressed (AirPrimary) handled by RushPlayfield.
[runtime] 2020-07-20 06:39:04 [debug]: KeyDownEvent(F, False) handled by RulesetInputManager<T>+RulesetKeyBindingContainer<RushAction>.
[runtime] 2020-07-20 06:39:05 [verbose]: Unhandled exception has been denied .
Unhandled exception. [runtime] 2020-07-20 06:39:05 [error]: An unhandled error has occurred.
[runtime] 2020-07-20 06:39:05 [error]: System.MissingFieldException: Field not found: 'osu.Game.Rulesets.Judgements.DrawableJudgement.Result'.
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Game.Rulesets.UI.JudgementContainer`1.Add(T judgement) in /home/ontake/Apps/Games/osu!lazer/osu/osu.Game/Rulesets/UI/JudgementContainer.cs:line 21
[runtime] 2020-07-20 06:39:05 [error]: at osu.Game.Rulesets.Rush.UI.RushPlayfield.onNewResult(DrawableHitObject judgedObject, JudgementResult result)
System.MissingFieldException: Field not found: 'osu.Game.Rulesets.Judgements.DrawableJudgement.Result'.
   at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
   at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
   at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
   at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
   at osu.Game.Rulesets.UI.JudgementContainer`1.Add(T judgement) in /home/ontake/Apps/Games/osu!lazer/osu/osu.Game/Rulesets/UI/JudgementContainer.cs:line 21
   at osu.Game.Rulesets.Rush.UI.RushPlayfield.onNewResult(DrawableHitObject judgedObject, JudgementResult result)
   at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.<apply>b__61_0(DrawableHitObject d, JudgementResult r) in /home/ontake/Apps/Games/osu!lazer/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 196
   at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.ApplyResult(Action`1 application) in /home/ontake/Apps/Games/osu!lazer/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 473
   at osu.Game.Rulesets.Rush.Objects.Drawables.DrawableNoteSheetHead.CheckForResult(Boolean userTriggered, Double timeOffset)
   at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.UpdateResult(Boolean userTriggered) in /home/ontake/Apps/Games/osu!lazer/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 491
   at osu.Game.Rulesets.Rush.Objects.Drawables.DrawableNoteSheetCap`1.UpdateResult(Boolean userTriggered)
   at osu.Game.Rulesets.Rush.Objects.Drawables.DrawableNoteSheet.OnPressed(RushAction action)
   at osu.Framework.Input.Bindings.KeyBindingContainer`1.<>c__DisplayClass19_0.<PropagatePressed>b__1(IKeyBindingHandler`1 d)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.Bindings.KeyBindingContainer`1.PropagatePressed(IEnumerable`1 drawables, T pressed, Single scrollAmount, Boolean isPrecise)
   at osu.Framework.Input.Bindings.KeyBindingContainer`1.handleNewPressed(InputState state, InputKey newKey, Boolean repeat, Nullable`1 scrollDelta, Boolean isPrecise)
   at osu.Framework.Input.Bindings.KeyBindingContainer`1.Handle(UIEvent e)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.KeyEventManager.HandleButtonDown(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonDown(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleKeyboardKeyStateChange(ButtonStateChangeEvent`1 keyboardKeyStateChange)
   at osu.Game.Rulesets.UI.RulesetInputManager`1.HandleInputStateChange(InputStateChangeEvent inputStateChange) in /home/ontake/Apps/Games/osu!lazer/osu/osu.Game/Rulesets/UI/RulesetInputManager.cs:line 77
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.PassThroughInputManager.SyncInputState(InputState state)
   at osu.Framework.Input.PassThroughInputManager.Handle(UIEvent e)
   at osu.Game.Rulesets.UI.RulesetInputManager`1.Handle(UIEvent e) in /home/ontake/Apps/Games/osu!lazer/osu/osu.Game/Rulesets/UI/RulesetInputManager.cs:line 125
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.KeyEventManager.HandleButtonDown(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonDown(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleKeyboardKeyStateChange(ButtonStateChangeEvent`1 keyboardKeyStateChange)
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass96_0.<handleException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.ThreadRunner.RunMainLoop()
   at osu.Framework.Platform.GameHost.windowUpdate()
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osuTK.GameWindow.Run()
   at osu.Framework.Platform.GameWindow.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /home/ontake/Apps/Games/osu!lazer/osu/osu.Desktop/Program.cs:line 55[runtime] 2020-07-20 06:39:05 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.<apply>b__61_0(DrawableHitObject d, JudgementResult r) in /home/ontake/Apps/Games/osu!lazer/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 19
6
[runtime] 2020-07-20 06:39:05 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.ApplyResult(Action`1 application) in /home/ontake/Apps/Games/osu!lazer/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 473
[runtime] 2020-07-20 06:39:05 [error]: at osu.Game.Rulesets.Rush.Objects.Drawables.DrawableNoteSheetHead.CheckForResult(Boolean userTriggered, Double timeOffset)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.UpdateResult(Boolean userTriggered) in /home/ontake/Apps/Games/osu!lazer/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 491
[runtime] 2020-07-20 06:39:05 [error]: at osu.Game.Rulesets.Rush.Objects.Drawables.DrawableNoteSheetCap`1.UpdateResult(Boolean userTriggered)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Game.Rulesets.Rush.Objects.Drawables.DrawableNoteSheet.OnPressed(RushAction action)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.<>c__DisplayClass19_0.<PropagatePressed>b__1(IKeyBindingHandler`1 d)
[runtime] 2020-07-20 06:39:05 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
[runtime] 2020-07-20 06:39:05 [error]: at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.PropagatePressed(IEnumerable`1 drawables, T pressed, Single scrollAmount, Boolean isPrecise)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.handleNewPressed(InputState state, InputKey newKey, Boolean repeat, Nullable`1 scrollDelta, Boolean isPrecise)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.Handle(UIEvent e)
[runtime] 2020-07-20 06:39:05 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
[runtime] 2020-07-20 06:39:05 [error]: at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Input.KeyEventManager.HandleButtonDown(InputState state, List`1 targets)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Input.ButtonEventManager`1.handleButtonDown(InputState state)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Input.InputManager.HandleKeyboardKeyStateChange(ButtonStateChangeEvent`1 keyboardKeyStateChange)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Game.Rulesets.UI.RulesetInputManager`1.HandleInputStateChange(InputStateChangeEvent inputStateChange) in /home/ontake/Apps/Games/osu!lazer/osu/osu.Game/Rulesets/UI/RulesetInputManager.cs:line 77
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
[runtime] 2020-07-20 06:39:05 [error]: at osu.Framework.Input.PassThroughInputManager.SyncInputState(InputState state)
```

**Comment by LumpBloom7** [comment]
This is due to the changes in judgements osu-side. And can simply be resolved with a dependency update.

**Comment by TechAdvancedCyborg** [comment]
making similar changes should fix it right? https://github.com/LumpBloom7/sentakki/commit/0e48ee837aedc170d362f66a0b13ac89c13e5fa8

**Comment by LumpBloom7** [comment]
Yes, it would.

**Comment by TechAdvancedCyborg** [comment]
I did it locally, testing it

**Comment by TechAdvancedCyborg** [comment]
oh wait gonna rebuild osu

**Comment by TechAdvancedCyborg** [comment]
new error: 2020-07-20 13:09:35 [error]: System.MissingFieldException: Field not found: 'osu.Game.Rulesets.Judgements.DrawableJudgement.JudgementBody'.

**Comment by LumpBloom7** [comment]
1. This is not a good place to talk about stuff like this, discord seems to be a better place for this matter
2. I've already got it working, will PR.

**Comment by TechAdvancedCyborg** [comment]
thx

**Comment by TechAdvancedCyborg** [comment]
Yup tested it, and crash is gone, thx!
